[project]
name = "dashboards-plotly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=2.18.2",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
]
